<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49" started-at="2014-05-10T13:49:51Z" finished-at="2014-05-10T13:49:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49" started-at="2014-05-10T13:49:51Z" finished-at="2014-05-10T13:49:51Z">
      <class name="com.epam.training.PaymentMachine.PaymentMachineTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.epam.training.PaymentMachine.PaymentMachineTest@5fe5c6f]" name="setup" is-config="true" duration-ms="14" started-at="2014-05-10T15:49:51Z" finished-at="2014-05-10T15:49:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testAddCoin()[pri:0, instance:com.epam.training.PaymentMachine.PaymentMachineTest@5fe5c6f]" name="testAddCoin" duration-ms="13" started-at="2014-05-10T15:49:51Z" finished-at="2014-05-10T15:49:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2500] but found [2000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2500] but found [2000]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:265)
	at org.testng.Assert.assertEquals(Assert.java:275)
	at com.epam.training.PaymentMachine.PaymentMachineTest.testAddCoin(PaymentMachineTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddCoin -->
      </class> <!-- com.epam.training.PaymentMachine.PaymentMachineTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
